### ISSUE TITLE
Missing string Privacy Policy

### ISSUE THREAD

**Issue by artpoli** [mozilla-l10n/appstores#28]
The following string is missing from the localization in android_42_release.lang:
Privacy Policy: http://www.mozilla.org/legal/privacy/firefox.html

I found it here https://l10n.mozilla-community.org/~pascalc/stores_l10n/locale/uk/google/next/

Usually "Privacy Policy" is localizable in other projects and I think it also should be translated here.

**Comment by flodolo** [comment]
(cc @pascalchevrel) This string is available for the AppStore (iOS), but I'm not sure if it's needed for Android, that's why it's displayed in English for all locales.

**Comment by artpoli** [comment]
If you take a look bellow this string (Google Play Next Screenshots Copy), there are additional four blocks without localization.

**Comment by TheoChevalier** [comment]
Missing strings have been added, closing the issue
