### ISSUE TITLE
EN-gb dashboard

### ISSUE THREAD

**Issue by satdav** [mozilla-l10n/appstores#67]
@pascalchevrel  or @flodolo any chance of looking into the en-gb dashboard as its showing what android_release.lang  needs updated but according to pontoon this does not its been pushed to github 2 weeks ago is this something one of you can fix

**Comment by flodolo** [comment]
The dashboard is reporting an error
https://l10n.mozilla-community.org/webdashboard/?locale=en-GB

You should click on it and fix it
https://l10n.mozilla-community.org/langchecker/?locale=en-GB#android_release.lang

**Comment by satdav** [comment]
@flodolo why is it not reporting it on pontoon as a error is this something what you can flag

**Comment by flodolo** [comment]
That's a question for Pontoon, not all the information is available there, right now you should always check the dashboard for errors and deadlines.

**Comment by satdav** [comment]
I can understand that If I know what string it is I can find it on pontoon and fix it that way

**Comment by satdav** [comment]
@flodolo  I see what has happened would this be a easy fix as Ian has put the full word for something rather than the short word so it must be a error at Mozilla end

**Comment by flodolo** [comment]
Have you clicked the second link? The error is reported at the end of the page

```
Get the customisable, private & free mobile browser that synchronises across devices.
Currently 85 characters long (maximum allowed 80)
```

https://github.com/mozilla-l10n/appstores/blob/master/en-GB/android_release.lang#L13

We don't make the rules for length limits on Google Play Store, so there's nothing we can do on our side
