### ISSUE TITLE
About the wording in apple_description_release.lang

### ISSUE THREAD

**Issue by yfdyh000** [mozilla-l10n/appstores#7]
I did not find the right place, so to write here.

https://github.com/mozilla-l10n/appstores/blob/master/en-US/apple_description_release.lang
I feel that the current promo wording maybe have some conflict.

Like the `voted the Most Trusted Internet Company for Privacy.` and `That’s why we design the product with smart features that take the guesswork out of browsing.`, the latter may sounds contrary to the principles of privacy and Do Not Track, the `Firefox anticipates your needs and ...` also well.

**Comment by flodolo** [comment]
Hi, we're only responsible for the localization of the content. For the actual content creation, the right process is to file a bug in Bugzilla. I guess Marketing::Copy could be a good start, ccing mhan(at)mozilla.com (responsible for Mobile's marketing).

Having said that, I don't think these sentences are in conflict. Mozilla uses data to improve the browsing experience, that doesn't mean it violates user privacy. For example Telemetry is opt-in, and collected data are aggregated.

**Comment by yfdyh000** [comment]
Thanks for the quick response. I wish to consider the views of others, because this is just my feeling during localization. It is not a question.

**Comment by yfdyh000** [comment]
After careful consideration, I intend to give up submitting a bug.

It's just I had misunderstood for "guesswork out" and "predictive", it don't contain a "precise analysis" meaning, but my translation words have a extended meaning. I will try to replace a more gentle words for my language. Thank you.
